name : CI/CD Process

on:
  push:
    branches:
      - master


jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Running Unit Test
      run: go test ./... -cover
      
  build-push-docker:
    name: Build and Push Docker to DockerHub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build -t rioputroo/acp:latest .
      
    - name: Login DockerHub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Push Docker Registry
      run: docker push rioputroo/acp:latest
